### ISSUE TITLE
Add standard files for all the repositories

### ISSUE THREAD

**Issue by elwoujdi** [ai-cfia/repo-template#1]
## Summary

In order to facilitate the development process and simplify the workflow for developers, we are creating this repository template. This template will include all the standard files necessary for starting a new project, ensuring consistency and efficiency across repositories.

## Tasks

- [x] Add standard files

**Comment by rngadam** [comment]
@ibrahim-kabir checklist?

**Comment by elwoujdi** [comment]
> @ibrahim-kabir checklist?

Has been updated
